
# % KRI4 COMPLIANCE = DIVIDE(EOL_MITIGATIONS[## TEMPORARY MITIGATION TOTAL (C19)], EOL_MITIGATIONS[## KRI4 DENOMINATOR(B21)]) + 0


## TEMPORARY MITIGATION TOTAL (C19) = CALCULATE(
    count( 'EOL_MITIGATIONS'[server_name] ) + 0
    ,FILTER('EOL_MITIGATIONS', 'EOL_MITIGATIONS'[## RESERVE STATUS CATEGORY] = "Complete" ),
FILTER('EOL_MITIGATIONS', 'EOL_MITIGATIONS'[## REMEDIATION PLAN CATEGORY] = "Temporary Remediation Plan"))


## KRI4 DENOMINATOR(B21) = EOL_MITIGATIONS[## KRI4 REMAINING EOL ALL (B20)] + EOL_MITIGATIONS[## TEMPORARY MITIGATION TOTAL (C19)]

## KRI4 REMAINING EOL ALL (B20) = CALCULATE(
    count( 'EOL_MITIGATIONS'[server_name]) + 0
    ,'EOL_MITIGATIONS'[## RESERVE STATUS CATEGORY] = "Remaining" 
)

## TEMPORARY MITIGATION TOTAL (C19) = CALCULATE(
    count( 'EOL_MITIGATIONS'[server_name] ) + 0
    ,FILTER('EOL_MITIGATIONS', 'EOL_MITIGATIONS'[## RESERVE STATUS CATEGORY] = "Complete" ),
FILTER('EOL_MITIGATIONS', 'EOL_MITIGATIONS'[## REMEDIATION PLAN CATEGORY] = "Temporary Remediation Plan"))